mysql:
  image: mysql:5.7
  ports:
    - 3308:3306
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - ./tmp/mysql:/var/lib/mysql
    - ./resources/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./tmp/mysql/my.cnf:/etc/mysql/my.cf
nginx:
  image: nginx:stable-alpine
  volumes:
    - ./tmp/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./tmp/nginx/logs:/var/log/nginx
  ports:
    - 3380:80
