mysql:
  image: mysql:5.7
  ports:
    - 3308:3306
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - ./tmp/mysql:/var/lib/mysql
    - ./resources/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
